#!/usr/bin/env python3
"""Regenerate references.bib from every papers/<slug>/citation.bib fragment.

Idempotent. De-duplicates by cite key. Run after adding/editing papers.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPERS = ROOT / "papers"
OUT = ROOT / "references.bib"

KEY_RE = re.compile(r"@\w+\{([^,]+),")


def main() -> None:
    entries: dict[str, str] = {}
    order: list[str] = []
    for frag in sorted(PAPERS.glob("*/citation.bib")):
        text = frag.read_text(encoding="utf-8").strip()
        if not text:
            continue
        m = KEY_RE.search(text)
        key = m.group(1).strip() if m else frag.parent.name
        if key not in entries:
            order.append(key)
        entries[key] = text

    header = (
        "% references.bib — auto-generated by scripts/build_bib.py\n"
        "% Do not edit by hand; edit papers/<slug>/citation.bib and re-run.\n"
        f"% {len(order)} entries\n\n"
    )
    OUT.write_text(header + "\n\n".join(entries[k] for k in order) + "\n", encoding="utf-8")
    print(f"✓ wrote {OUT.relative_to(ROOT)} with {len(order)} entries")


if __name__ == "__main__":
    main()
